# Homebrew formula for rustemd. Lives in the `homebrew-rustemd` tap repo:
#
#   brew tap fralalonde/rustemd   # resolves to github.com/fralalonde/homebrew-rustemd
#   brew install rustemd
#
# The `url`/`sha256` fields are pinned per release and regenerated by
# scripts/gen-brew-formula.sh — do not hand-edit the sha256.
class Rustemd < Formula
  desc "A systemd init reimplementation: unit manager + systemctl-compatible CLI"
  homepage "https://github.com/fralalonde/rustemd"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fralalonde/rustemd/releases/download/v0.1.0/rustemd-0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fralalonde/rustemd/releases/download/v0.1.0/rustemd-0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_arm do
      url "https://github.com/fralalonde/rustemd/releases/download/v0.1.0/rustemd-0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "bin/rustemd", "bin/rustemctl", "bin/rustemd-tui"
    bash_completion.install "completions/rustemctl.bash" => "rustemctl"
    zsh_completion.install "completions/_rustemctl"
    fish_completion.install "completions/rustemctl.fish"
  end

  test do
    assert_match "rustemd", shell_output("#{bin}/rustemd --version")
    assert_match "rustemctl", shell_output("#{bin}/rustemctl --version")
  end
end
