#!/usr/bin/env bash
# Regenerate Formula/rustemd.rb for a release: fetch the release tarballs,
# compute their sha256, and rewrite the formula. Run AFTER the release assets
# are published (i.e. after release.sh tags + CI finishes uploading).
#
# Usage: scripts/gen-brew-formula.sh <version>     # e.g. 0.1.0
set -euo pipefail

VERSION="${1:?version required (e.g. 0.1.0)}"
BASE="https://github.com/fralalonde/rustemd/releases/download/v${VERSION}"

sha256_of() {
    local url="$1"
    if command -v sha256sum >/dev/null 2>&1; then
        curl -fsSL "$url" | sha256sum | cut -d' ' -f1
    else
        curl -fsSL "$url" | shasum -a 256 | cut -d' ' -f1
    fi
}

linux_x86="$(sha256_of "$BASE/rustemd-$VERSION-x86_64-unknown-linux-gnu.tar.gz")"
linux_arm="$(sha256_of "$BASE/rustemd-$VERSION-aarch64-unknown-linux-gnu.tar.gz")"
mac_arm="$(sha256_of "$BASE/rustemd-$VERSION-aarch64-apple-darwin.tar.gz")"

cat > Formula/rustemd.rb <<EOF
# Homebrew formula for rustemd. Tap it from the project repo:
#
#   brew tap fralalonde/rustemd https://github.com/fralalonde/rustemd
#   brew install rustemd
#
# The \`url\`/\`sha256\` fields are pinned per release and regenerated by
# scripts/gen-brew-formula.sh — do not hand-edit the sha256.
class Rustemd < Formula
  desc "A systemd init reimplementation: unit manager + systemctl-compatible CLI"
  homepage "https://github.com/fralalonde/rustemd"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_arm do
      url "$BASE/rustemd-$VERSION-aarch64-apple-darwin.tar.gz"
      sha256 "$mac_arm"
    end
  end

  on_linux do
    on_intel do
      url "$BASE/rustemd-$VERSION-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "$BASE/rustemd-$VERSION-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "bin/rustemd", "bin/rustemd-tui"
    bash_completion.install "completions/rustemd.bash" => "rustemd"
    zsh_completion.install "completions/_rustemd"
    fish_completion.install "completions/rustemd.fish"
  end

  test do
    assert_match "rustemd", shell_output("#{bin}/rustemd --version")
  end
end
EOF

echo "wrote Formula/rustemd.rb for v$VERSION"
