#!/usr/bin/env bash
# Build an Alpine APK from already-built static musl binaries.
#
# Usage: scripts/package-alpine.sh <target-triple> <version>
#   e.g. scripts/package-alpine.sh x86_64-unknown-linux-musl 0.2.1
#
# The package is intentionally unsigned. Release signing can be added by the
# release job without making local, rootless builds depend on a private key.
# Installers must use apk's --allow-untrusted flag until a public signing key
# is published and configured by the project.
set -euo pipefail

TARGET="${1:?target triple required}"
VERSION="${2:?version required}"

case "$TARGET" in
    x86_64-unknown-linux-musl) APK_ARCH=x86_64 ;;
    aarch64-unknown-linux-musl) APK_ARCH=aarch64 ;;
    *) echo "unsupported target: $TARGET" >&2; exit 2 ;;
esac

case "$VERSION" in
    ''|*[!0-9.]*|.*|*.)
        echo "version must contain only numeric dot-separated components: $VERSION" >&2
        exit 2
        ;;
esac

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BIN_DIR="$ROOT/target/$TARGET/release"
DIST="$ROOT/dist"
PKGVER="$VERSION-r0"
APK="$DIST/rystemd-$PKGVER-$APK_ARCH.apk"
STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

for binary in rystemd rystemctl rystemd-tui; do
    [ -x "$BIN_DIR/$binary" ] || {
        echo "missing executable: $BIN_DIR/$binary" >&2
        exit 1
    }
done
command -v python3 >/dev/null || {
    echo "python3 is required to build an APK" >&2
    exit 2
}

mkdir -p "$DIST" "$STAGE/data/usr/bin" \
    "$STAGE/data/usr/share/bash-completion/completions" \
    "$STAGE/data/usr/share/zsh/site-functions" \
    "$STAGE/data/usr/share/fish/vendor_completions.d" \
    "$STAGE/control"
install -m 0755 "$BIN_DIR/rystemd" "$STAGE/data/usr/bin/rystemd"
install -m 0755 "$BIN_DIR/rystemctl" "$STAGE/data/usr/bin/rystemctl"
install -m 0755 "$BIN_DIR/rystemd-tui" "$STAGE/data/usr/bin/rystemd-tui"
ln -s rystemctl "$STAGE/data/usr/bin/systemctl"

"$BIN_DIR/rystemctl" completions bash \
    > "$STAGE/data/usr/share/bash-completion/completions/rystemctl"
"$BIN_DIR/rystemctl" completions zsh \
    > "$STAGE/data/usr/share/zsh/site-functions/_rystemctl"
"$BIN_DIR/rystemctl" completions fish \
    > "$STAGE/data/usr/share/fish/vendor_completions.d/rystemctl.fish"

SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-$(git -C "$ROOT" log -1 --format=%ct)}"
export STAGE PKGVER APK_ARCH SOURCE_DATE_EPOCH APK
python3 - <<'PY'
import gzip
import hashlib
import io
import math
import os
import tarfile

stage = os.environ["STAGE"]
pkgver = os.environ["PKGVER"]
arch = os.environ["APK_ARCH"]
epoch = int(os.environ["SOURCE_DATE_EPOCH"])


def normalize(info):
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    info.mtime = epoch
    return info


def tar_segment(root, arcname, include_end=False, checksums=False):
    output = io.BytesIO()
    tar_format = tarfile.PAX_FORMAT if checksums else tarfile.USTAR_FORMAT

    def prepare(info):
        normalize(info)
        if checksums and (info.isfile() or info.issym()):
            relative = os.path.relpath(info.name, arcname)
            source = os.path.join(root, relative)
            if info.issym():
                payload = os.readlink(source).encode()
            else:
                with open(source, "rb") as input_file:
                    payload = input_file.read()
            info.pax_headers["APK-TOOLS.checksum.SHA1"] = hashlib.sha1(
                payload
            ).hexdigest()
        return info

    with tarfile.open(fileobj=output, mode="w", format=tar_format) as archive:
        archive.add(root, arcname=arcname, recursive=True, filter=prepare)
    raw = output.getvalue()
    if include_end:
        return raw
    # APK v2 concatenates tar segments. Remove exactly the two end records,
    # while preserving file padding and trailing zero bytes in file contents.
    with tarfile.open(fileobj=io.BytesIO(raw), mode="r:") as archive:
        members = archive.getmembers()
        used = max(
            member.offset + 512 + math.ceil(member.size / 512) * 512
            for member in members
        )
    return raw[:used]


data_segment = tar_segment(
    os.path.join(stage, "data", "usr"), "usr", include_end=True, checksums=True
)
data_gzip = gzip.compress(data_segment, compresslevel=9, mtime=epoch)
size = sum(
    member.size
    for member in tarfile.open(fileobj=io.BytesIO(data_segment), mode="r:").getmembers()
    if member.isfile()
)
datahash = hashlib.sha256(data_gzip).hexdigest()

pkginfo = f"""# Generated by scripts/package-alpine.sh
pkgname = rystemd
pkgver = {pkgver}
pkgdesc = A readable systemd-compatible service manager in Rust
url = https://github.com/rystemd/rystemd
builddate = {epoch}
packager = rystemd release automation
size = {size}
arch = {arch}
origin = rystemd
maintainer = Francis Lalonde
license = MIT
provides = cmd:rystemd={pkgver}
provides = cmd:rystemctl={pkgver}
datahash = {datahash}
""".encode()

control_root = os.path.join(stage, "control", ".PKGINFO")
with open(control_root, "wb") as output:
    output.write(pkginfo)
control_segment = tar_segment(control_root, ".PKGINFO")
control_gzip = gzip.compress(control_segment, compresslevel=9, mtime=epoch)

with open(os.environ["APK"], "wb") as output:
    output.write(control_gzip)
    output.write(data_gzip)
PY

cp "$APK" "$DIST/rystemd-$APK_ARCH.apk"
echo "created $APK"
echo "created $DIST/rystemd-$APK_ARCH.apk"